C:\Users\333da\Desktop\FEFU\Djonson\pascal\pascal.exe -t test/000.in
C:\Users\333da\Desktop\FEFU\Djonson\pascal\pascal.exe -t test/001.in
C:\Users\333da\Desktop\FEFU\Djonson\pascal\pascal.exe -t test/002.in
C:\Users\333da\Desktop\FEFU\Djonson\pascal\pascal.exe -t test/003.in
C:\Users\333da\Desktop\FEFU\Djonson\pascal\pascal.exe -t test/004.in
C:\Users\333da\Desktop\FEFU\Djonson\pascal\pascal.exe -t test/005.in
C:\Users\333da\Desktop\FEFU\Djonson\pascal\pascal.exe -t test/006.in
C:\Users\333da\Desktop\FEFU\Djonson\pascal\pascal.exe -t test/007.in
C:\Users\333da\Desktop\FEFU\Djonson\pascal\pascal.exe -t test/008.in
C:\Users\333da\Desktop\FEFU\Djonson\pascal\pascal.exe -t test/009.in
C:\Users\333da\Desktop\FEFU\Djonson\pascal\pascal.exe -t test/010.in
C:\Users\333da\Desktop\FEFU\Djonson\pascal\pascal.exe -t test/011.in
C:\Users\333da\Desktop\FEFU\Djonson\pascal\pascal.exe -t test/012.in
C:\Users\333da\Desktop\FEFU\Djonson\pascal\pascal.exe -t test/013.in
